objects/DelegatedToken__c.object
<CustomObject>
    <fields>
        <fullName>RequestIP__c</fullName>
        <label>Request IP</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <externalId>true</externalId>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delegated Token</label>
    <nameField>
        <displayFormat>DT{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegated Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RESTDelegatedAuthenticator.cls
@RestResource(urlMapping='/delegatedAuth')
global without sharing class RESTDelegatedAuthenticator {
    
    @HttpPost
    global static void getOpenCases() {
        RestResponse response = RestContext.response;
        response.statusCode = 200;
        response.addHeader('Content-Type', 'application/xml');
        Boolean authResult = false;
        try{
            Dom.Document doc = new DOM.Document(); 
            doc.load(RestContext.request.requestBody.toString());  
            DOM.XMLNode root = doc.getRootElement();
            Map<String,String> requestValues = walkThrough(root);
            
            
            authResult = checkCredentials(requestValues.get('username'), 
                                          requestValues.get('password'),
                                          requestValues.get('sourceIp'));
        }catcH(Exception e){
            //authResult = true;
            insert new Log__c(Description__c = e.getStackTraceString()+'\n'+e.getMessage(), 
                       Request__c = RestContext.request.requestBody.toString());
        }finally{
            //authResult = true;
            insert new Log__c(Description__c = 'Result:'+authResult, 
                       Request__c = RestContext.request.requestBody.toString());
        }
        String soapResp = '<?xml version="1.0" encoding="UTF-8"?>'
            +'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">'
            +'<soapenv:Body>'
            +'<AuthenticateResult xmlns="urn:authentication.soap.sforce.com">'
            +'<Authenticated>'+authResult+'</Authenticated>'
            +'</AuthenticateResult>'
            +'</soapenv:Body>'
            +'</soapenv:Envelope>';
        response.responseBody = Blob.valueOf(soapResp);
    }
    
    /*
* Checks current username / token / IP and garbages all old token (created < NOW-3 mins)
*/
    private static Boolean checkCredentials(String username, String token, String ip){
        delete [Select Id From DelegatedToken__c Where CreatedDate < :System.now().addMinutes(-3)];
        List<DelegatedToken__c> dTList =  [Select Id From DelegatedToken__c Where Username__c = :username
                                           and RequestIP__c = :ip and Token__c = :token];
        if(dTList.size()>0){
            //delete the found token
            delete dTList;
            return true;
        }
        return false;
    }
    
    /*
    * Gets all text elements of the DOM
    */
    private static map<String,String> walkThrough(DOM.XMLNode node) {
        map<String,String> tempMap = new map<String,String>();
        if (node.getNodeType() == DOM.XMLNodeType.ELEMENT) {
            if (node.getText().trim() != '') {
                tempMap.put(node.getName(), node.getText());
            }
            for (Dom.XMLNode child: node.getChildElements()) {
                tempMap.putAll(walkThrough(child));
            }
        }
        return tempMap; 
    }
    
}