objects/DelegatedToken__c.object
<CustomObject>
    <fields>
        <fullName>RequestIP__c</fullName>
        <label>Request IP</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <externalId>true</externalId>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delegated Token</label>
    <nameField>
        <displayFormat>DT{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegated Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DelegatedUser__c.object
<CustomObject>
    <fields>
        <fullName>DelegatedUsername__c</fullName>
        <label>Delegated Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegated_ORG_ID__c</fullName>
        <description>Remote ORG ID</description>
        <label>Delegated ORG ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocalUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Delegated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delegated User</label>
    <nameField>
        <displayFormat>DU{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegated Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelegateLoginController.cls
public class DelegateLoginController { 
    /*
     * Helper class to handle different delegated users
     */
    public class DelegatedUser{
        
        public DelegatedUser(DelegatedUser__c usr){
            this.usr = usr;
        }
        
        public DelegatedUser__c usr{get;set;}
        
        public PageReference delegateAuthentication(){
            String password = generateGUID();
            insert new DelegatedToken__c(Token__c = password, 
                                      Username__c = this.usr.DelegatedUsername__c,
                                      RequestIP__c = getCurrentIP());
            String url = 'https://login.salesforce.com/login.jsp?'
                        +'un='+EncodingUtil.urlEncode(this.usr.DelegatedUsername__c, 'utf8')
                        +'&orgId='+this.usr.Delegated_ORG_ID__c 
                        +'&pw='+EncodingUtil.urlEncode(password, 'utf8')
                		+'&rememberUn=0&jse=0';
            //you can also setup a startURL, logoutURL and ssoStartPage parameters to enhance usre experience
            PageReference page = new PageReference(url);
            page.setRedirect(false);
            return page;
        }
    }
    
    /*
     * List of all delegated users
     */
    public List<DelegatedUser> users{get;set;}
    
    /*
     * Constructor
	 */
    public DelegateLoginController(){
        this.users = new List<DelegatedUser>();
        for(DelegatedUser__c du : [Select Id, DelegatedUsername__c, Delegated_ORG_ID__c
                                  	From DelegatedUser__c Where LocalUser__c = :UserInfo.getUserId()
                                   Order by DelegatedUsername__c]){
        	this.users.add(new DelegatedUser(du));                               
		}
    }
    
    /*
     * GUID generator
     */
    public static String generateGUID(){
        Blob b = Crypto.GenerateAESKey(128);
		String h = EncodingUtil.ConvertTohex(b);
		return h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' 
            	+ h.SubString(12,16) + '-' + h.SubString(16,20) 
            	+ '-' + h.substring(20);
    }
    
    /*
     * Gets current user's IP
     */
    public static String getCurrentIP(){
        Map<String, String> mapHeaders = ApexPages.currentPage().getHeaders();   
        String ipAddress;
        if(mapHeaders != null) {
            ipAddress = mapHeaders.get('True-Client-IP');
            if(ipAddress == null){
                ipAddress = mapHeaders.get('X-Salesforce-SIP');
            }
        }
        return ipAddress;
    }
}